services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - qr-attendance-network
networks:
  qr-attendance-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local