services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-attendance-app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/attendance_db
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always
    networks:
      - qr-attendance-network
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    ports:
      - "25432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - qr-attendance-network
networks:
  qr-attendance-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local